import Foundation
import Combine

/// Provenance is recorded on every entry. There is no fourth category, and no
/// entry exists without one.
enum Provenance: String, Codable {
    case casualty = "Casualty-entered"
    case device = "Device-measured"
    case wearable = "Wearable-derived"
    case protocolAsserted = "Protocol-asserted"
    case dictated = "Casualty dictated · structured by model · committed by core"

    var display: String { rawValue }
}

struct LedgerEntry: Identifiable, Codable {
    let id: UUID
    /// Minutes since point of injury, generated by the device. Never recalled by
    /// the casualty.
    let minute: Int
    /// Monotonic wall clock at the moment of commit, for forensic ordering.
    let stamped: Date
    let name: String
    let detail: String
    let provenance: Provenance
    let protocolVersion: String?
    /// Corrections are new entries referencing the one they supersede. Nothing is
    /// overwritten and nothing is deleted.
    let supersedes: UUID?

    init(minute: Int, name: String, detail: String, provenance: Provenance,
         protocolVersion: String? = nil, supersedes: UUID? = nil) {
        self.id = UUID()
        self.minute = minute
        self.stamped = Date()
        self.name = name
        self.detail = detail
        self.provenance = provenance
        self.protocolVersion = protocolVersion
        self.supersedes = supersedes
    }
}

/// Append-only, local, durable before the interface acknowledges it. Cold
/// shutdown without warning is documented platform behaviour with no published
/// threshold, so every write is checkpointed to disk synchronously — an
/// in-memory entry is not an entry.
@MainActor
final class LedgerStore: ObservableObject {
    @Published private(set) var entries: [LedgerEntry] = []

    private let url: URL = {
        let dir = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
        try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        return dir.appendingPathComponent("ledger.json")
    }()

    init() {
        load()
        if entries.isEmpty { entries = LedgerStore.seed }
    }

    /// The only write path. The language layer has no access to it: it proposes a
    /// structured candidate and the deterministic core commits it.
    func append(_ entry: LedgerEntry) {
        entries.append(entry)
        checkpoint()
    }

    func append(minute: Int, name: String, detail: String,
                provenance: Provenance, protocolVersion: String? = nil) {
        append(LedgerEntry(minute: minute, name: name, detail: detail,
                           provenance: provenance, protocolVersion: protocolVersion))
    }

    var reversed: [LedgerEntry] { entries.reversed() }

    private func checkpoint() {
        do {
            let data = try JSONEncoder().encode(entries)
            // .atomic + .completeFileProtection: durable, and encrypted at rest.
            try data.write(to: url, options: [.atomic, .completeFileProtection])
        } catch {
            // A failed checkpoint is a clinical failure, not a logging concern.
            // Surface it in the UI in production rather than swallowing it here.
            assertionFailure("Ledger checkpoint failed: \(error)")
        }
    }

    private func load() {
        guard let data = try? Data(contentsOf: url),
              let decoded = try? JSONDecoder().decode([LedgerEntry].self, from: data) else { return }
        entries = decoded
    }

    /// Wipe-on-command. A captured device is an intelligence document.
    func wipe() {
        entries = []
        try? FileManager.default.removeItem(at: url)
    }

    static let seed: [LedgerEntry] = [
        LedgerEntry(minute: 4, name: "Tourniquet applied", detail: "Right thigh, CAT, windlass ×3", provenance: .casualty),
        LedgerEntry(minute: 6, name: "Outcome confirmed", detail: "Bleeding stopped, distal pulse absent", provenance: .device),
        LedgerEntry(minute: 41, name: "Analgesia", detail: "Fixed-dose card, pouch 1 of 7", provenance: .protocolAsserted, protocolVersion: ProtocolBundle.version),
        LedgerEntry(minute: 70, name: "Wound packed", detail: "Left axilla, 3:00 continuous pressure held", provenance: .device),
        LedgerEntry(minute: 135, name: "Reposition", detail: "Left lateral", provenance: .casualty),
        LedgerEntry(minute: 180, name: "Vitals session", detail: "HR 112, RR 22, radial pulse present", provenance: .device),
        LedgerEntry(minute: 260, name: "Reposition", detail: "Supine", provenance: .casualty),
        LedgerEntry(minute: 302, name: "Urine volume", detail: "180 ml since T+001:00", provenance: .casualty)
    ]
}
